import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#4edea3",
        "on-primary-fixed-variant": "#3c475b",
        "surface-container-low": "#f5f3f5",
        "primary": "#000000",
        "on-tertiary-fixed-variant": "#005236",
        "on-secondary-fixed": "#2a1700",
        "outline-variant": "#c5c6cd",
        "surface": "#fbf8fa",
        "secondary": "#855300",
        "inverse-primary": "#bbc7df",
        "outline": "#75777d",
        "on-background": "#1b1b1d",
        "surface-container": "#f0edef",
        "surface-variant": "#e4e2e3",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#ffb95f",
        "secondary-container": "#fea619",
        "on-secondary-container": "#684000",
        "on-error-container": "#93000a",
        "primary-fixed": "#d7e3fc",
        "on-surface": "#1b1b1d",
        "surface-container-high": "#eae7e9",
        "on-primary": "#ffffff",
        "surface-tint": "#535f74",
        "secondary-fixed": "#ffddb8",
        "on-tertiary-container": "#009668",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#002113",
        "background": "#fbf8fa",
        "surface-dim": "#dcd9db",
        "on-surface-variant": "#45474c",
        "inverse-on-surface": "#f3f0f2",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#bbc7df",
        "surface-container-highest": "#e4e2e3",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#303032",
        "error-container": "#ffdad6",
        "surface-bright": "#fbf8fa",
        "tertiary-fixed": "#6ffbbe",
        "on-primary-fixed": "#101c2e",
        "on-secondary-fixed-variant": "#653e00",
        "on-primary-container": "#79849b",
        "primary-container": "#101c2e",
        "tertiary-container": "#002113"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "16px",
        "base": "4px",
        "xl": "64px",
        "lg": "40px",
        "xs": "8px",
        "md": "24px",
        "unit-md": "16px",
        "gutter": "24px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "unit-xl": "48px",
        "unit-lg": "24px",
        "unit-sm": "8px",
        "unit-xs": "4px"
      },
      fontFamily: {
        "headline-xl-mobile": ["var(--font-sora)", "Sora", "sans-serif"],
        "headline-lg": ["var(--font-sora)", "Sora", "sans-serif"],
        "headline-xl": ["var(--font-sora)", "Sora", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "data-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-sm": ["var(--font-sora)", "Sora", "sans-serif"],
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-sora)", "Sora", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-sora)", "Sora", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "data-mono": ["var(--font-inter)", "Inter", "sans-serif"]
      },
      fontSize: {
        "headline-xl-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "data-md": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "headline-sm": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "14px", "fontWeight": "500"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "data-mono": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
export default config;
